#' @param anInteger integer - fusion of hour and minute
#'
#' @return string - a time label in format 'hh:mm uur'
#' 
convertIntegerToTimeLabel <- function(anInteger) {

  charactersList <- strsplit(as.character(anInteger), NULL)[[1]]
  lengthOfExpr <- length(charactersList)
  
  reversedList <- rev(charactersList)
  
  timeLabelList <- rev(c(reversedList[1:2], ":", reversedList[3:lengthOfExpr]))
  
  timeLabel <- paste(timeLabelList, collapse = '')
  
  paste0(timeLabel, " uur")
}

#' @param aDate date of flight
#' @param numberOfSeats numeric - maximum available seats
#'
#' @return vectorised integer representing a number of seats occupied at a certain date
#' 
computeOccupancy <- function(aDate, numberOfSeats) {
  case_when(
    aDate == ymd('2013-01-31') | aDate == ymd('2013-02-06') ~ floor(.88*numberOfSeats),
    aDate == ymd('2013-02-01') | aDate == ymd('2013-02-05') ~ floor(.95*numberOfSeats),
    aDate == ymd('2013-02-02') | aDate == ymd('2013-02-04') ~ numberOfSeats,
    aDate == ymd('2013-02-03') ~ floor(.45*numberOfSeats),
    aDate < ymd('2013-06-29') ~ floor(.75*numberOfSeats),
    aDate > ymd('2013-09-01') & aDate < ymd('2013-12-15') ~ floor(.75*numberOfSeats),
    aDate > ymd('2013-12-14') & aDate < ymd('2013-12-25') ~ floor(.92*numberOfSeats),
    aDate == ymd('2013-12-25') ~ floor(.55*numberOfSeats),
    aDate > ymd('2013-12-25') & aDate < ymd('2014-01-01') ~ floor(.87*numberOfSeats),
    TRUE ~ numberOfSeats
  )
}

#' @param aNumber numeric - arbitrary IncNodePurity representing feature importance 
#'
#' @return string - hex colour code
#' 
defineColours <- function(aNumber) {
  case_when(
    aNumber > 1000000 ~ "#8B0000",
    aNumber < 1000000 & aNumber > 550000 ~ "#CD853F",
    TRUE ~ "#6B8E23"
  )
}

#' @param anInteger integer - representing number of (+/-) minutes a flight was delayed
#'
#' @return string - <span> tag displaying delayed minutes in either green or red
#' 
displayDelay <- function(anInteger) {
  
  if_else(anInteger >= 0, 
          paste0('<span style="color:#008000"> + ', anInteger,' mins</span>'),
          paste0('<span style="color:#B22222"> ', anInteger,' mins</span>'))
}

#' @param aDistanceInMiles numeric - distance between two airports
#'
#' @return string - description including the distance in kms and the time it would take sound to travel that distance at 20ªC (:
#' 
displayDistanceInKms <- function(aDistanceInMiles) {
  
  distanceInKms <- aDistanceInMiles*1.609344
  
  timeIfVelocityThatOfSound <- distanceInKms/1234.8
  
  paste0(as.character(round(distanceInKms,digits = 2)), 
         ' kms. (', 
         round(timeIfVelocityThatOfSound, digits = 2),
         ' uur met geluidssnelheid)')
}

#' @param aDataset tibble - data frame containing features and their importance
#'
#' @return bar plot generated by ggplot
#' 
generateImportancePlot <- function(aDataset) {
  aDataset %>%
    ggplot(aes(x = parameter, y = importance)) +
    geom_bar(stat = "identity", fill = defineColours(aDataset$importance)) +
    ggtitle("Wat in hoever vertraging bepaald") +
    xlab("") + ylab("") +
    theme(plot.title = element_text(size = 18, face = "bold", hjust = 0.5)) +
    theme(axis.title.x = element_text(size = 16, face = "bold")) +
    theme(axis.title.y = element_text(size = 16, face = "bold")) +
    theme(axis.text.x= element_blank()) +
    theme(axis.text.y= element_text(face = "bold", size = 12, angle = 15)) +
    coord_flip()
}

#' @param aCode string - three-letter code standing for one of the NY airports
#'
#' @return string - a path to a csv file in app/data containing feature importance data
#' 
getPathForOrigin <- function(aCode) {
  case_when(
    aCode == 'EWR' ~ pathToEWRDataModelII,
    aCode == 'JFK' ~ pathToJFKDataModelII,
    aCode == 'LGA' ~ pathToLGADataModelII,
    TRUE ~ pathToEWRDataModelII
  )
}

#' @param type string - one of two types
#' @param anOrigin three-letter code of an airport
#' @param fromDate first date in date range
#' @param toDate second date in date range
#'
#' @return string - tirle for the scatter/bar plot generated by ggplot
#' 
getTitleForPlot <- function(type = c("occupancy", "capacity"), anOrigin, fromDate, toDate) {
  type <- match.arg(type)
  
  head <- switch(type,
         "occupancy" = "Aantal passagiers per dag vanaf ",
         "capacity" = "% van totale capaciteit in ")
  
  paste0(head, anOrigin, "\n",
         "(Periode: ", fromDate, " t/m ", toDate, ")")
}

#' @param aQuery string - prepared query string for flights
#' @param needsFlightFilter boolean - whether or not the query filters by flight number
#' @param aFlight integer - a flight number
#' @param needsOriginFilter boolean - whether or not the query filters by origin
#' @param origins character vector containing three-letter codes of origins
#'
#' @return string - plain query after parameters in prepared query have been replaced
#' 
interpolateFlightsQuery <- function(aQuery,
                                    needsFlightFilter,
                                    aFlight,
                                    needsOriginFilter,
                                    origins) {
  
  # Decide how to insert the query parameters
  if(needsFlightFilter & needsOriginFilter) {
    
    sqlInterpolate(ANSI(), aQuery, .dots = list(flight = aFlight, origins = SQL(origins)))
    
  } else if (needsFlightFilter & !needsOriginFilter) {
    
    sqlInterpolate(ANSI(), aQuery, flight = aFlight)
    
  } else if (!needsFlightFilter & needsOriginFilter) {
    
    sqlInterpolate(ANSI(), aQuery, origins = SQL(origins))
    
  } else {
    
    aQuery
  }
}



#' @return JavaScript expression applied to datatable just after initialisation
#' 
jsHeader <- JS("function(settings, json) {",
               "$(this.api().table().header()).css({'background-color':'#2F4F4F','color': '#FFF0F5'});",
               "}")

#' @param aPathToDataset string - the path to a dataset containing feature importance data
#'
#' @return tibble - data frame containing 2 columns: parameter & feature importance
#' 
readAndFormatData <- function(aPathToDataset) {
  read.csv(aPathToDataset, 
           header = TRUE, 
           sep = ";", 
           dec = ",",
           stringsAsFactors = FALSE) %>%
    as_tibble() %>%
    transmute(parameter = X %>% as.factor(),
              importance = IncNodePurity) %>%
    mutate(parameter = reorder(parameter, importance))
}

#' @param aLookUpTable named vector 
#' @param aCode string - contained in the values of the named vector
#'
#' @return string corresponding to the name of a particular value
#' 
writeDestinationDisplayName <- function(aLookUpTable, aCode) {
  
  if_else(is.na(unname(aLookUpTable[aCode])),
          aCode,
          paste0(unname(aLookUpTable[aCode]), " (", aCode, ")")
          )
}

#' @return string - plain query used to retrieve airports from DB
#' 
writeQueryForAirpots <- function() {
  "SELECT faa, name 
  FROM airports;"
}

#' @param anOrigin string - three-letter code of an airport
#'
#' @return string - prepared query used to retrieve all destinations 
#' (including coords) corresponding to an origin
#' 
writeQueryForDestinations <- function(anOrigin) {
  
  query <- "SELECT faa, name, lat, lon
  FROM airports 
  WHERE faa IN 
  (
    SELECT DISTINCT dest 
    FROM
    (
      SELECT * 
        FROM flights 
      WHERE origin = ?origin
    ));"
  
  
  sqlInterpolate(ANSI(), query, origin = anOrigin)
}

#' @param aFlight integer - a flight number
#' @param origins character vector containing three-letter codes
#'
#' @return string - plain query used to retrieve flights from DB
#' 
writeQueryForFlightsWithFilters <- function(aFlight, origins) {
  
  # Write base select statement with no clauses
  baseQuery <- "SELECT flight_id, time_hour, dep_time, sched_dep_time, dep_delay, arr_time,
  sched_arr_time, arr_delay, carrier, tailnum, flight, origin, dest, distance FROM flights"

  # Check whether flight filter is being applied
  needsFlightFilter <- !is.na(aFlight)
  
  # Check whether origins filter is being given
  needsOriginFilter <- !identical(character(0), origins)
  
  if(needsOriginFilter) {
    # Write each origin in a quoted list for SQL to understand it
    origins <- sprintf("(%s)", toString(sprintf("'%s'", origins)))
  }
  
  whereClause <- writeWhereClause(needsFlightFilter, needsOriginFilter)
  query <- paste0(baseQuery, whereClause)
  
  query %>%
    interpolateFlightsQuery(needsFlightFilter, aFlight, needsOriginFilter, origins)

}

#'
#' @return string - plain query used to retrieve info on departing airports (including coords)
#' 
writeQueryForOrigins <- function() {
  "SELECT faa, name, lat, lon
  FROM airports 
  WHERE faa IN 
  (
  SELECT DISTINCT origin 
  FROM flights
  );"
}

#' @param anOrigin string - three-letter code of an airport
#' @param aDate1 first date in date range
#' @param aDate2 second date in date range
#'
#' @return string - plain query returning origin, time_hour, seats and tailnum from DB
#' 
writeQueryForSeats <- function(anOrigin, aDate1, aDate2) {
  query <- "SELECT *
  FROM (
  SELECT f.tailnum, origin, time_hour, seats 
  FROM flights f
  INNER JOIN planes p ON f.tailnum = p.tailnum
  )
  WHERE origin = ?origin AND time_hour BETWEEN date(?date1) AND date(?date2);"
  
  sqlInterpolate(ANSI(), query, .dots = list(origin = anOrigin, date1 = aDate1, date2 = aDate2))
}

#' @param needsFlightFilter boolean - whether or not a query applies a flight filter
#' @param needsOriginFilter boolean - whether or not a query applies a filter for origins
#'
#' @return string - WHERE clause to be appended to another query
#' 
writeWhereClause <- function(needsFlightFilter,
                             needsOriginFilter) {
  
  case_when(
    needsFlightFilter & needsOriginFilter ~ " WHERE flight = ?flight AND origin IN ?origins;",
    needsFlightFilter & !needsOriginFilter ~ " WHERE flight = ?flight;",
    !needsFlightFilter & needsOriginFilter ~ " WHERE origin IN ?origins;",
    TRUE ~ ";"
  )
}